Add donor criteria field
dinovski/ICDOT pull request #22
Opened 2022-01-19 09:32 UTC by dinovski

2022-03-02 14:00 UTC, wapiflapi requested changes

2022-03-02 14:00 UTC, wapiflapi commented on bhot/transplants/models/transplant.py
> +        null=True,
CharField with null

2022-03-02 15:26 UTC, wapiflapi commented on bhot/transplants/models/sequencing.py
> +    transplant = models.ForeignKey(Transplant, null=True, on_delete=models.SET_NULL)
We will be using the `run_date` instead. We will have to update this where identity is concerned.

2022-03-02 18:14 UTC, dinovski commented on bhot/transplants/models/biopsy.py
> +        null=True,
units are only required if there is an entry for dose so I will leave it as is for now.

2022-03-02 18:14 UTC, dinovski commented on bhot/transplants/models/histology.py
> +        ADEQUATE = "arteriolar", _("arteriolar")
nope :)

2022-03-03 09:23 UTC, dinovski commented on bhot/transplants/models/sequencing.py
> +    transplant = models.ForeignKey(Transplant, null=True, on_delete=models.SET_NULL)
removed transplant, it was a copy/paste error.

2022-03-15 15:52 UTC, merged